name: "[TEST] with paths"

on:
  workflow_dispatch:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  single-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"

      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          extensions: pytest-asyncio
          paths: tests/test_true.py

  multiple-paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"

      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          extensions: pytest-asyncio
          paths: |
            tests/test_false.py \
            tests/test_true.py

  glob-pattern:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"

      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          extensions: pytest-asyncio
          paths: tests/**.py
