name: "[TEST] with show"

on:
  workflow_dispatch:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  show-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"

      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          extensions: pytest-asyncio
          show: all

  show-none:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"

      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          extensions: pytest-asyncio
          show: none
